##############################################################################
# PLAY 0 ─ Controller prep: choose ONE dump folder for the whole run
##############################################################################
- name: Initialise controller dump folder
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create shared dump directory and expose its path
      set_fact:
        ctl_metrics_dir: "/tmp/metrics_dump/{{ lookup('pipe','date +%Y%m%d_%H%M%S') }}"

    - name: Ensure the directory exists
      file:
        path: "{{ ctl_metrics_dir }}"
        state: directory
        mode: "0755"

##############################################################################
# PLAY 1 ─ Run “Network Outage” scenario on every Pi and fetch resource logs
##############################################################################
- name: Run “Network Outage" scenario on all farmslug Pis
  hosts: all
  gather_facts: no
  vars:
    runners:   3
    runtime_before_outage:  30 
    outage_duration:        30 
    test_plan: ../taprunner/Baseline.TapPlan
    reg_token: CHANGE_ME
    repo_dir:  ~/KeysightTestAutomation
    script:    test-scripts/network_outage.sh
  tasks:
  # ──────────────────────────────────────────────────────────────────────────
  - name: Stash local changes (static label)
    shell: |
      cd {{ repo_dir }}
      if git diff --quiet && git diff --cached --quiet ; then
          echo "NO_STASH"
      else
          prev_ref=$(git stash list | awk -F: '$2 ~ /ansible-run/ {print $1; exit}')
          [ -n "$prev_ref" ] && git stash drop --quiet "$prev_ref"
          git stash push -m "ansible-run" --quiet
          git stash list | head -n 1 | cut -d: -f1
      fi
    register: stash_status
    changed_when: "'NO_STASH' not in stash_status.stdout"

  - name: Ensure repo is up-to-date
    shell: git -C {{ repo_dir }} pull --rebase --autostash --quiet
    changed_when: false

  # ── run the scenario ─────────────────────────────────────────────────────
  - name: Run the Network Outage script
    shell: |
      cd {{ repo_dir }}
      chmod +x {{ script }}
      ./{{ script }} {{ runners }} {{ runtime_before_outage }} {{ outage_duration }} {{ test_plan }} {{ reg_token }}
    async: 7200
    poll: 0
    register: job

  - name: Wait for script to finish
    async_status:
      jid: "{{ job.ansible_job_id }}"
    register: job_status
    until: job_status.finished
    retries: 720
    delay: 10

  # ── pull per-host runtime summary (unchanged) ────────────────────────────
  - name: Compute per-host summary (fastest / slowest / avg runtime)
    shell: |
      metrics_root="$HOME/KeysightTestAutomation/metrics"
      latest="$(ls -1td "$metrics_root"/* 2>/dev/null | head -1)"
      if [ -z "$latest" ]; then printf "0,0,0" && exit 0; fi
      awk -F',' '/runtime=/{split($0,a,"runtime=");sum+=a[2];c++; \
          if(min==""||a[2]<min)min=a[2]; if(a[2]>max)max=a[2]} \
          END{printf "%s,%s,%s",min,max,(c?sum/c:0)}' \
          "$latest"/*_metrics.log
    register: host_summary
    changed_when: false

  - name: Save numbers as a fact on THIS host
    set_fact:
      script_runtimes:
        fastest: "{{ host_summary.stdout.split(',')[0] | float }}"
        slowest: "{{ host_summary.stdout.split(',')[1] | float }}"
        average: "{{ host_summary.stdout.split(',')[2] | float }}"

  - name: Show raw script_runtimes on this host
    debug:
      var: script_runtimes

  # ── copy resource-usage log to controller ────────────────────────────────
  - name: Find newest networkOutage metrics folder
    shell: ls -1td "$HOME/KeysightTestAutomation/metrics"/networkOutage_* 2>/dev/null | head -1
    register: latest_run_dir
    changed_when: false

  - name: Stat resource_usage.log
    stat:
      path: "{{ latest_run_dir.stdout }}/resource_usage.log"
    register: res_log

  - name: Fetch resource_usage.log to controller (if present)
    fetch:
      src:  "{{ latest_run_dir.stdout }}/resource_usage.log"
      dest: "{{ hostvars['localhost'].ctl_metrics_dir }}/{{ inventory_hostname }}_resource_usage.log"
      flat: true
    when: res_log.stat.exists

  # ── restore any stashed changes ──────────────────────────────────────────
  - name: Pop the stash we created earlier (if any)
    shell: |
      cd {{ repo_dir }}
      ref="{{ stash_status.stdout | trim }}"
      [ "$ref" != "NO_STASH" ] && git stash pop --quiet "$ref"
    changed_when: false
    when: stash_status.stdout is defined and stash_status.stdout | trim != "NO_STASH"

##############################################################################
# PLAY 2 ─ Controller: merge fetched logs into one Influx line-protocol file
##############################################################################
- name: Build InfluxDB dump from fetched resource logs
  hosts: localhost
  gather_facts: no
  vars:
    dump_file: "{{ ctl_metrics_dir }}/influxdump_{{ lookup('pipe','date +%Y%m%d_%H%M%S') }}.lp"
  tasks:
    - name: Convert logs ➜ Influx line protocol
      shell: |
        outfile="{{ dump_file }}"
        : > "$outfile"
        shopt -s nullglob
        for f in "{{ ctl_metrics_dir }}"/*_resource_usage.log; do
          [ -e "$f" ] || continue
          host="$(basename "$f" | cut -d'_' -f1)"
          awk -F',' -v host="$host" 'NR>1{
              ts_ns = $1 "000000000";
              cpu=$2; mem=$3;
              rd=($4==""?0:$4); wr=($5==""?0:$5);
              rx=($6==""?0:$6); tx=($7==""?0:$7);
              load=$8;
              printf "pi_resources,host=%s,cpu_percent=%s,memory_kb=%s,disk_io_read_kb=%s,"\
              "disk_io_write_kb=%s,network_rx_bytes=%s,network_tx_bytes=%s,load_avg=%s,timestamp=%s\n",\
              host,cpu,mem,rd,wr,rx,tx,load,ts_ns;
          }' "$f" >> "$outfile"
        done
      args:
        executable: /bin/bash
      changed_when: true

    - debug:
        msg: "Combined InfluxDB dump written to {{ dump_file }}"