---
- name: Run “Active Lab” scenario on all farmslug Pis
  hosts: all
  gather_facts: no
  vars:
    runners:            3                # how many OpenTAP runners to spin up
    simulation_time:    300              # seconds the lab stays active
    test_plan:          /home/pi/Baseline.TapPlan
    reg_token:          CHANGE_ME
    repo_dir:           ~/KeysightTestAutomation
    script:             test-scripts/active_lab.sh
  tasks:

  - name: Stash local changes (static label)
    ansible.builtin.shell: |
      cd {{ repo_dir }}

      # If the working tree and index are already clean, signal “no stash”.
      if git diff --quiet && git diff --cached --quiet ; then
          echo "NO_STASH"
      else
          prev_ref=$(git stash list | awk -F: '$2 ~ /ansible-run/ {print $1; exit}')
          [ -n "$prev_ref" ] && git stash drop --quiet "$prev_ref"

          # Push current changes with the fixed label.
          git stash push -m "ansible-run" --quiet

          # Grab the ref of the stash we just created (top of the list).
          git stash list | head -n 1 | cut -d: -f1
      fi
    register: stash_status
    changed_when: "'NO_STASH' not in stash_status.stdout"

  - name: Ensure repo is up-to-date
    ansible.builtin.shell: git -C {{ repo_dir }} pull --rebase --autostash --quiet
    changed_when: false

  # ------------------------------------------------------------------
  # 2. kick off active_lab.sh asynchronously (so we don’t block forks)
  # ------------------------------------------------------------------
  - name: Run the Active Lab script
    ansible.builtin.shell: |
      cd {{ repo_dir }}
      ./{{ script }} {{ runners }} {{ simulation_time }} {{ test_plan }} {{ reg_token }}
    async:  10800        # allow up to 3 h
    poll:   0
    register: job

  - name: Wait for script to finish
    ansible.builtin.async_status:
      jid: "{{ job.ansible_job_id }}"
    register: job_status
    until: job_status.finished
    retries: 1080        # check every 10 s → 3 h max
    delay:   10

  # ------------------------------------------------------------------
  # 3. pull a per-host summary from the newest Active Lab metrics folder
  # ------------------------------------------------------------------
  - name: Compute per-host summary (fastest / slowest / avg runner-average)
    ansible.builtin.shell: |
      metrics_root="$HOME/KeysightTestAutomation/metrics"
      latest="$(ls -1td "$metrics_root"/activeLab_* 2>/dev/null | head -1)"

      # if nothing found, return zeros
      if [ -z "$latest" ]; then
        printf "0,0,0" && exit 0
      fi

      awk -F',' '
        /avg_runtime=/ {
          for (i = 1; i <= NF; i++)
            if ($i ~ /avg_runtime=/) { split($i,a,"="); avg=a[2] }
          sum += avg; c++
          if (min=="" || avg < min) min = avg
          if (avg > max)            max = avg
        }
        END { printf "%s,%s,%s", min, max, (c ? sum/c : 0) }
      ' "$latest"/runner_*_metrics.log
    register: host_summary
    changed_when: false

  - name: Save numbers as a fact on THIS host
    ansible.builtin.set_fact:
      active_lab_runtimes:
        fastest: "{{ host_summary.stdout.split(',')[0] | float }}"
        slowest: "{{ host_summary.stdout.split(',')[1] | float }}"
        average: "{{ host_summary.stdout.split(',')[2] | float }}"

  # ------------------------------------------------------------------
  # 4. show what we captured for this host
  # ------------------------------------------------------------------
  - name: Show raw active_lab_runtimes on this host
    debug:
      var: active_lab_runtimes

  - name: Pop the stash we created earlier (if any)
    ansible.builtin.shell: |
      cd {{ repo_dir }}
      ref="{{ stash_status.stdout | trim }}"
      [ "$ref" != "NO_STASH" ] && git stash pop --quiet "$ref"
    changed_when: false
    when: stash_status.stdout is defined and stash_status.stdout | trim != "NO_STASH"
