

# To run this playbook:
# ansible-playbook -i "$(../test_scripts/generate_inventory.sh)" run_cleanup_metrics.yml --extra-vars "days_old={days}"


---
- name: Cleanup old metrics folders across all farmslug Pis
  hosts: all
  gather_facts: no
  vars:
    days_old: 7 
    repo_dir: ~/KeysightTestAutomation
    cleanup_script: test_scripts/cleanup_metrics.sh
  tasks:

  - name: Ensure repo is up-to-date (git pull)
    ansible.builtin.shell: git -C {{ repo_dir }} pull --quiet
    changed_when: false

  - name: Run the cleanup script
    ansible.builtin.shell: |
      cd {{ repo_dir }}/test_scripts
      ./cleanup_metrics.sh {{ days_old }}
    args:
      chdir: "{{ repo_dir }}/test_scripts"
    register: cleanup_result
    changed_when: "'Deleted' in cleanup_result.stdout"

  - name: Show cleanup output on this host
    debug:
      var: cleanup_result.stdout